from . import contract_cost_type
from . import cost_type
from . import kiosk_kiosk
from . import kiosk_electric_number
from . import kiosk_water_number
from . import kiosk_contract
from . import kiosk_payment
from . import kiosk_payment_line
from . import res_partner
